### PR TITLE
make nextbot "understand" multiple jira IDs in one message

### PR DESCRIPTION
**Pull request by phueper**

### CODE REVIEW

**Comment by hpurmann** [comment]
Thanks for sending this PR. Nice feature addition, wanted to do this as well at some point.

* Please run `npm run lint` once again. Some of the code is not following our style guide.
* Please squash feature commits with lint commits
* I'd prefer to have real system(/integration) tests instead of the regex tests because the test structure looks non-intuitive. I tried to use [hubot-test-helper](https://github.com/mtsmfm/hubot-test-helper) for this, but unfortunately it only works in coffeescript code bases since `hubot` itself is _[published as CoffeeScript](https://github.com/mtsmfm/hubot-test-helper/issues/33)_. Really weird. Maybe we can find a good solution on this?

**Comment by phueper** [comment]
i linted and squashed :) 

i agree that real integration tests would be nice... but using this workaround for the regex tests, we can unit test just the regex which has a value in itself imho

**Comment by hpurmann** [comment]
Let's add integration tests at some other point. Merged.

Btw: Creating a branch is best practice when sending a PR since it makes it easier for others to check out your changes.

**Comment by phueper** [comment]
Thx for merging. 

I did fork, so my branch is available right here: https://github.com/phueper/hubot/tree/master  
;)

And a PR can easily be checkout out as well: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by phueper** [comment]
ah... i was too slow understanding... i should've created a branch in my repo named for the "feature" that i was working on... ACK :)

**Comment by hpurmann** [comment]
:+1: :grin:

**Pull request merged**
